title: Himsjø drar på tutbærtbil-ferie
description: [Få den bilen i flyttegiret og kjør meg til Namsos]
remote_theme: "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon"
header:
  teaser: /assets/images/norge.jpg
plugins: 
  - jekyll-include-cache
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true
