remote_theme: "mmistakes/minimal-mistakes@4.19.3"
minimal_mistakes_skin: "neon" # "air", "aqua", "contrast", "dark", "dirt", "neon"

locale: "en-US"
classes: wide
title: "Sommer 2020"
description: &description "Få den bilen i flyttegiret og kjør meg til Namsos"
# subtitle: "Få den bilen i flyttegiret og kjør meg til Namsos"
plugins: 
  - jekyll-include-cache
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: splash
      read_time: true
      author_profile: true
      comments: true
      share: true
      related: true
